name: ci

on:
  push:
    branches:
     - 'dsl2'
     - 'orca-249-push-to-ghcr'
    paths:
     - 'docker/**'
     - '.github/workflows/ci.yml'

jobs:
      docker:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './docker'
        steps:
          - name: Checkout GitHub Action
            uses: actions/checkout@v3

          - name: Login to GitHub Container Registry (GHCR)
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build Inventory Image'
            run: |
              docker build . --tag ghcr.io/adamjtaylor/htan-artist:latest
              docker push ghcr.io/adamjtaylor/htan-artist:latest


