name: ci

on:
  push:
    branches:
     - 'dsl2'
     - 'orca-249-push-to-ghcr'
    paths:
     - 'docker/**'
     - '.github/workflows/ci.yml'

jobs:
      docker:
        permissions: write-all
        runs-on: ubuntu-latest

        steps:
          - name: Checkout GitHub Action
            uses: actions/checkout@v3

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1

          - name: Login to GitHub Container Registry (GHCR)
            uses: docker/login-action@v2
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}
              logout: false

          - name: Build and push to GHCR
            uses: docker/build-push-action@v4
            with:
              context: .
              file: ./docker/Dockerfile
              push: true
              tags: ghcr.io/adamjtaylor/htan-artist:latest


