name: ci

on:
  push:
    branches:
     - 'dsl2'
     - 'orca-249-push-to-ghcr'
    paths:
     - 'docker/**'
     - '.github/workflows/ci.yml'

jobs:
      docker:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write
          id-token: write

        defaults:
          run:
            working-directory: './docker'

        steps:
          - name: Checkout GitHub Action
            uses: actions/checkout@v3

          - name: Login to GitHub Container Registry (GHCR)
            uses: docker/login-action@v2
            with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}

          - name: Build and push to GHCR
            uses: docker/build-push-action@v4
            with:
              context: ./docker
              file: ./docker/Dockerfile
              push: true
              tags: ghcr.io/adamjtaylor/htan-artist:latest


