name: ci

on:
  push:
    branches:
     - 'dsl2'
     - 'orca-249-push-to-ghcr'
    paths:
     - 'docker/**'
     - '.github/workflows/ci.yml'

jobs:
      docker:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './docker'
        steps:
          - name: Checkout GitHub Action
            uses: actions/checkout@v3

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1

          - name: Login to GitHub Container Registry (GHCR)
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}
              logout: false

          - name: Build and push to GHCRg
            uses: docker/build-push-action@v4
            with:
              context: ./docker
              push: true
              tags: |
                adamjtaylor/htan-artist:latest
                ghcr.io/adamjtaylor/htan-artist:latest


