name: ci

on:
  push:
    branches:
     - 'dsl2'
    paths:
     - 'docker/**'
     - '.github/workflows/ci.yml'

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
      docker:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write
          id-token: write
          pull-requests: write

        defaults:
          run:
            working-directory: './docker'

        steps:
          - name: Checkout GitHub Action
            uses: actions/checkout@v3

          - name: Login to GitHub Container Registry (GHCR)
            uses: docker/login-action@v2
            with:
              registry: ${{ env.REGISTRY }}
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}
              
          - name: Extract Docker metadata
            id: metadata
            uses: docker/metadata-action@v4
            with:
              images: ${{ env.REGISTRY }}/${{ github.repository }}
              tags: |
                type=semver,pattern={{version}}
                type=semver,pattern={{major}}.{{minor}} 
                type=semver,pattern={{major}}
                type=sha
                latest

          - name: Build and push to GHCR
            uses: docker/build-push-action@v4
            with:
              context: ./docker
              file: ./docker/Dockerfile
              push: true
              tags: ${{ steps.metadata.outputs.tags }}
              labels: ${{ steps.metadata.outputs.labels }}
