name: Run pipeline
on:
  push:
    branches:
      - "main"
      - "nextflow-action"
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nf-core/setup-nextflow@v1
      - run: nextflow run ${GITHUB_WORKSPACE} --input data/test_samplesheet.csv 