name: Run nf-artist test data

on:
  pull_request:
    branches: 'main'
    paths: 'HTAN.model.csv'
  workflow_dispatch:

jobs:
  nf-artist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nf-core/setup-nextflow@v1
      - run: nextflow run ${GITHUB_WORKSPACE} --input data/test_samplesheet.csv